name: Deply to server

on: push

jobs: 
  first_jobs:
    name: Nombre personalizado para ver en el dashboard de Github
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  second_jobs:
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Aca va"

