name: Deply to server

on: push

jobs: 
  first_jobs:
    name: Nombre personalizado para ver en el dashboard de Github
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  second_jobs:
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Aca va"
      - run: echo "Vamos a usar un contexto para saber desde que rama se hizo push ${{ github.ref	 }}"


  third_jobs:
    name: Job que utilliza una acción de Github
    runs-on: ubuntu-latest

    steps:
      - name: Acción para saber el directorio de trabajo
        uses: actions/checkout@v4

